-- Drop the test table (you'll have to comment it out the first time this is called)
DROP TABLE test;

-- Create the test table
CREATE TABLE test (
  ID INTEGER GENERATED ALWAYS AS IDENTITY,
  F_BOOL NUMBER(1),
  F_CHAR CHAR(3),
  F_NCHAR NCHAR(3),
  F_VARCHAR2  VARCHAR2(100 CHAR),
  F_NVARCHAR2 NVARCHAR2(100),
  F_NUMBER NUMBER(10, 4),
  F_FLOAT FLOAT(4),
  F_DATE DATE,
  F_BINARY_FLOAT BINARY_FLOAT,
  F_BINARY_DOUBLE BINARY_DOUBLE,
  F_TIMESTAMP TIMESTAMP,
  F_RAW RAW(16),
  F_LONG_RAW LONG RAW,
  F_ROWID ROWID,
  F_CLOB CLOB,
  F_BLOB BLOB,
  PRIMARY KEY(ID)
);